### PR TITLE
Merge PR for #15

### PR DESCRIPTION
**Pull request by morgangallant**
Getting #15 in, don't have write access to the downstream repo, so rebasing changes / test updates need to be made here

Thank you so much @boarush for contributing, very much apologize this review took so long, will make an effort to review any future PRs much, much faster <3

### CODE REVIEW

**Comment by sirupsen** [comment]
1. What throughput do you get here?
2. Can you fix the Python test problem on master in tpuf's CLI that uses this client?
3. There's another dependency problem with current master that causes some issue with [the notebook](https://colab.research.google.com/drive/17i4sfFTeJQkINCxjBaOGOZeENZr4ZaTE) we share; can you try with this branch?
4. Does this use the same client for async and non-async (i'd prefer it this way for less overhead)?

**Comment by boarush** [comment]
To address @sirupsen's 4th point, it is not possible rn to use the same client for both async and sync usage (in httpx at least AFAIK).

**Comment by pushrax** [comment]
Just had a read through this code, and I think we need a followup. There's a large amount of duplicated code that's likely to drift as further changes are made. The duplicated code should be factored into shared functions for the sync / async paths. Some examples:

- code to convert input types to API request payloads
- code to convert API responses to python return values
- code to handle errors
- code to parse server timing

I'm also not sure it makes sense to expose sync/async versions of functions on the same objects, maybe better to have separate types for them (with shared underlying code for all of the above). But I'm not as sure about that.

maybe @fw42 can take a stab at cleaning this up

**Comment by pushrax** [comment]
I realized I never posted why this was reverted, the main issue wasn't the code structure, but it broke our CI by causing the machines to run out of memory. Here's the explanation I came up with (reposting an internal Slack message):

> ok I've worked out the issue:
> - for every namespace in the list response, we create a Namespace object
> - each new Namespace eagerly creates a Backend and as of the recent changes, an AsyncBackend
> - these calls each create an httpx.Client / httpx.AsyncClient
> - creating a client loads the TLS CA bundle, which is slow and uses a bunch of memory
> - there are 104k namespaces in the test organization so this adds up quickly (and OOMs after a while before getting to 104k)
>
> there are also other issues with the httpx setup:
> - the httpx.Client types are really connection pools, and because we create a new one for every namespace object (unless one is passed in by the user), we don't connection pool properly
> - the async client possibly has a memory leak if you don't pass in a persistent client, due to https://bugs.python.org/issue40727
> I'm going to revert the commits that changed to httpx for now so we can do builds

**Pull request merged**
